#!/bin/bash

git clone https://github.com/mercadonanuvem/mercado

echo "Informe o nome do diretorio"
read newdir
`mv mercado $newdir`

(cd $newdir && composer install)

echo "Informe a url (ex: http://localhost/)"
read baseurl

echo "Banco de Dados (existente): Informe o host (ex: localhost)"
read dbhost

echo "Banco de Dados (existente): Informe o nome do banco de dados"
read dbname

echo "Banco de Dados (existente): Informe o usuario"
read dbuser

echo "Banco de Dados (existente): Informe a senha"
read dbpass

echo "Magento Admin (criar): Usuário"
read adminuser

echo "Magento Admin (criar): Senha (mais que 6 caracteres com letra(s) e numero(s))"
read adminpass

echo "Elasticsearch (existente): Informe o host (ex: localhost)"
read elastichost

(cd $newdir && bin/magento setup:install --base-url="$baseurl"  --db-host="$dbhost" --db-name="$dbname" --db-user="$dbuser" --db-password="$dbpass" --admin-firstname="Mercado" --admin-lastname="Na Nuvem" --admin-email="mercadonanuvem@gmail.com" --admin-user="$adminuser" --admin-password="$adminpass" --language="pt_BR" --currency="BRL" --timezone="America/Sao_Paulo" --use-rewrites="1" --elasticsearch-host="$elastichost")

chmod -R 777 $newdir

(cd $newdir && composer require rafaelstz/traducao_magento2_pt_br:dev-master)
(cd $newdir && bin/magento setup:static-content:deploy pt_BR -f)
(cd $newdir && bin/magento cache:clean)
(cd $newdir && bin/magento setup:di:compile)
